// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/jflex/lexer.flex

package analizador;
import analizador.Token;
import analizador.tokenConstante;



@SuppressWarnings("fallthrough")
public class Lexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\41\0\1\1\2\0\1\2\1\0\1\3\1\0\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\11\15\2\0\1\16\1\17\1\20\2\0\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\2\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\3\32\1\47\1\0\1\50"+
    "\3\0\7\32\1\51\22\32\1\52\1\53\1\54\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\4\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\11\1\12\1\13\1\14\12\15\1\16\1\17"+
    "\1\1\1\20\1\21\1\22\1\23\1\0\1\24\1\25"+
    "\1\26\5\15\1\27\6\15\1\30\1\0\5\15\1\31"+
    "\5\15\1\0\2\15\1\32\6\15\1\33\1\15\1\34"+
    "\1\0\3\15\1\35\1\15\1\36\3\15\1\0\1\15"+
    "\1\37\3\15\1\40\1\41\1\0\4\15\1\0\1\42"+
    "\2\15\2\0\1\43\1\15\2\0\1\15\17\0\1\44"+
    "\5\0\1\45\22\0\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\55\0\55\0\341"+
    "\0\55\0\55\0\55\0\55\0\u010e\0\u013b\0\u0168\0\u0195"+
    "\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd"+
    "\0\u032a\0\u0357\0\u0384\0\55\0\55\0\u03b1\0\55\0\55"+
    "\0\55\0\55\0\u03de\0\55\0\55\0\55\0\u040b\0\u0438"+
    "\0\u0465\0\u0492\0\u04bf\0\u021c\0\u04ec\0\u0519\0\u0546\0\u0573"+
    "\0\u05a0\0\u05cd\0\55\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae"+
    "\0\u06db\0\u021c\0\u0708\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9"+
    "\0\u0816\0\u0843\0\u021c\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u0924"+
    "\0\u0951\0\u021c\0\u097e\0\u021c\0\u09ab\0\u09d8\0\u0a05\0\u0a32"+
    "\0\u021c\0\u0a5f\0\u021c\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13\0\u0b40"+
    "\0\u021c\0\u0b6d\0\u0b9a\0\u0bc7\0\u021c\0\u021c\0\u0bf4\0\u0c21"+
    "\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u021c\0\u0d02\0\u0d2f\0\u0d5c"+
    "\0\u0d89\0\u021c\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97"+
    "\0\u0ec4\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff"+
    "\0\u102c\0\u1059\0\u1086\0\u10b3\0\u10e0\0\55\0\u110d\0\u113a"+
    "\0\u1167\0\u1194\0\u11c1\0\55\0\u11ee\0\u121b\0\u1248\0\u1275"+
    "\0\u12a2\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383\0\u13b0\0\u13dd"+
    "\0\u140a\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb\0\55";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\2\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\2\23\1\24\1\25\1\26\2\23\1\27"+
    "\5\23\1\30\1\23\1\31\1\32\1\33\3\23\1\34"+
    "\1\35\1\23\1\2\1\36\1\2\74\0\1\37\43\0"+
    "\1\40\51\0\1\41\53\0\1\42\66\0\2\16\33\0"+
    "\1\43\17\0\2\16\56\0\1\44\54\0\1\45\54\0"+
    "\1\46\51\0\2\23\3\0\12\23\1\47\13\23\2\0"+
    "\1\23\17\0\2\23\3\0\26\23\2\0\1\23\17\0"+
    "\2\23\3\0\4\23\1\50\21\23\2\0\1\23\17\0"+
    "\2\23\3\0\12\23\1\51\1\23\1\52\11\23\2\0"+
    "\1\23\17\0\2\23\3\0\12\23\1\53\13\23\2\0"+
    "\1\23\17\0\2\23\3\0\5\23\1\54\6\23\1\55"+
    "\11\23\2\0\1\23\17\0\2\23\3\0\20\23\1\56"+
    "\5\23\2\0\1\23\17\0\2\23\3\0\4\23\1\57"+
    "\21\23\2\0\1\23\17\0\2\23\3\0\7\23\1\60"+
    "\12\23\1\61\3\23\2\0\1\23\17\0\2\23\3\0"+
    "\7\23\1\62\16\23\2\0\1\23\56\0\1\63\5\0"+
    "\1\64\64\0\2\23\3\0\12\23\1\65\13\23\2\0"+
    "\1\23\17\0\2\23\3\0\2\23\1\66\23\23\2\0"+
    "\1\23\17\0\2\23\3\0\21\23\1\67\4\23\2\0"+
    "\1\23\17\0\2\23\3\0\3\23\1\70\22\23\2\0"+
    "\1\23\17\0\2\23\3\0\15\23\1\71\10\23\2\0"+
    "\1\23\17\0\2\23\3\0\22\23\1\72\3\23\2\0"+
    "\1\23\17\0\2\23\3\0\15\23\1\73\10\23\2\0"+
    "\1\23\17\0\2\23\3\0\16\23\1\74\7\23\2\0"+
    "\1\23\17\0\2\23\3\0\15\23\1\75\10\23\2\0"+
    "\1\23\17\0\2\23\3\0\20\23\1\76\5\23\2\0"+
    "\1\23\17\0\2\23\3\0\4\23\1\77\21\23\2\0"+
    "\1\23\55\0\1\100\16\0\2\23\3\0\4\23\1\101"+
    "\21\23\2\0\1\23\17\0\2\23\3\0\24\23\1\102"+
    "\1\23\2\0\1\23\17\0\2\23\3\0\4\23\1\103"+
    "\21\23\2\0\1\23\17\0\2\23\3\0\3\23\1\104"+
    "\4\23\1\105\5\23\1\106\7\23\2\0\1\23\17\0"+
    "\2\23\3\0\1\107\25\23\2\0\1\23\17\0\2\23"+
    "\3\0\6\23\1\110\17\23\2\0\1\23\17\0\2\23"+
    "\3\0\4\23\1\111\21\23\2\0\1\23\17\0\2\23"+
    "\3\0\25\23\1\112\2\0\1\23\17\0\2\23\3\0"+
    "\10\23\1\113\15\23\2\0\1\23\17\0\2\23\3\0"+
    "\14\23\1\114\11\23\2\0\1\23\27\0\1\115\44\0"+
    "\2\23\3\0\17\23\1\116\6\23\2\0\1\23\17\0"+
    "\2\23\3\0\1\117\25\23\2\0\1\23\17\0\2\23"+
    "\3\0\4\23\1\120\21\23\2\0\1\23\17\0\2\23"+
    "\3\0\5\23\1\121\20\23\2\0\1\23\17\0\2\23"+
    "\3\0\20\23\1\122\5\23\2\0\1\23\17\0\2\23"+
    "\3\0\22\23\1\123\3\23\2\0\1\23\17\0\2\23"+
    "\3\0\20\23\1\124\5\23\2\0\1\23\17\0\2\23"+
    "\3\0\1\125\25\23\2\0\1\23\17\0\2\23\3\0"+
    "\14\23\1\126\11\23\2\0\1\23\34\0\1\127\37\0"+
    "\2\23\3\0\23\23\1\130\2\23\2\0\1\23\17\0"+
    "\2\23\3\0\20\23\1\131\5\23\2\0\1\23\17\0"+
    "\2\23\3\0\2\23\1\132\23\23\2\0\1\23\17\0"+
    "\2\23\3\0\15\23\1\133\10\23\2\0\1\23\17\0"+
    "\2\23\3\0\1\134\25\23\2\0\1\23\17\0\2\23"+
    "\3\0\22\23\1\135\3\23\2\0\1\23\17\0\2\23"+
    "\3\0\6\23\1\136\17\23\2\0\1\23\32\0\1\137"+
    "\41\0\2\23\3\0\1\140\25\23\2\0\1\23\17\0"+
    "\2\23\3\0\24\23\1\141\1\23\2\0\1\23\17\0"+
    "\2\23\3\0\6\23\1\142\17\23\2\0\1\23\17\0"+
    "\2\23\3\0\13\23\1\143\12\23\2\0\1\23\34\0"+
    "\1\144\37\0\2\23\3\0\12\23\1\145\13\23\2\0"+
    "\1\23\17\0\2\23\3\0\1\146\25\23\2\0\1\23"+
    "\17\0\2\23\3\0\20\23\1\147\5\23\2\0\1\23"+
    "\15\0\1\150\1\0\2\23\3\0\26\23\2\0\1\23"+
    "\46\0\1\151\25\0\2\23\3\0\20\23\1\152\5\23"+
    "\2\0\1\23\17\0\2\23\3\0\1\153\25\23\2\0"+
    "\1\23\45\0\1\154\50\0\1\155\32\0\2\23\3\0"+
    "\13\23\1\156\12\23\2\0\1\23\30\0\1\157\103\0"+
    "\1\160\12\0\1\161\1\0\2\23\3\0\26\23\2\0"+
    "\1\23\26\0\1\162\104\0\1\163\43\0\1\164\55\0"+
    "\1\165\63\0\1\166\27\0\1\167\60\0\1\170\44\0"+
    "\1\171\56\0\1\172\67\0\1\173\72\0\1\174\43\0"+
    "\1\175\46\0\1\176\72\0\1\177\32\0\1\200\75\0"+
    "\1\201\40\0\1\202\40\0\1\203\67\0\1\204\73\0"+
    "\1\205\53\0\1\206\53\0\1\207\25\0\1\210\105\0"+
    "\1\211\53\0\1\212\53\0\1\213\26\0\1\214\104\0"+
    "\1\215\53\0\1\216\53\0\1\217\27\0\1\220\103\0"+
    "\1\221\53\0\1\222\53\0\1\223\30\0\1\224\102\0"+
    "\1\225\5\0\1\226\56\0\1\227\45\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5400];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\2\11\1\1\4\11\17\1\2\11"+
    "\1\1\4\11\1\0\3\11\14\1\1\11\1\0\13\1"+
    "\1\0\14\1\1\0\11\1\1\0\7\1\1\0\4\1"+
    "\1\0\3\1\2\0\2\1\2\0\1\1\17\0\1\11"+
    "\5\0\1\11\22\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token("ERROR", yytext());
            }
          // fall through
          case 39: break;
          case 2:
            { return new Token("INICIO_A", yytext());
            }
          // fall through
          case 40: break;
          case 3:
            { return new Token("FIN_A", yytext());
            }
          // fall through
          case 41: break;
          case 4:
            { return new Token("OP_PTO", yytext());
            }
          // fall through
          case 42: break;
          case 5:
            { return new Token("OP_ADC", yytext());
            }
          // fall through
          case 43: break;
          case 6:
            { return new Token("SEP_A", yytext());
            }
          // fall through
          case 44: break;
          case 7:
            { return new Token("OP_SUS", yytext());
            }
          // fall through
          case 45: break;
          case 8:
            { return new Token("OP_DIV", yytext());
            }
          // fall through
          case 46: break;
          case 9:
            { return new Token("CTE_INT", yytext());
            }
          // fall through
          case 47: break;
          case 10:
            { return new Token("CMP_MENOR", yytext());
            }
          // fall through
          case 48: break;
          case 11:
            { return new Token("OP_ASIG", yytext());
            }
          // fall through
          case 49: break;
          case 12:
            { return new Token("CMP_MAYOR", yytext());
            }
          // fall through
          case 50: break;
          case 13:
            { return new Token("ID", yytext());
            }
          // fall through
          case 51: break;
          case 14:
            { return new Token("INICIO_E", yytext());
            }
          // fall through
          case 52: break;
          case 15:
            { return new Token("FIN_E", yytext());
            }
          // fall through
          case 53: break;
          case 16:
            { return new Token("CMP_DTO", yytext());
            }
          // fall through
          case 54: break;
          case 17:
            { return new Token("INICIO_C", yytext());
            }
          // fall through
          case 55: break;
          case 18:
            { return new Token("CMP_CJN", yytext());
            }
          // fall through
          case 56: break;
          case 19:
            { return new Token("FIN_C", yytext());
            }
          // fall through
          case 57: break;
          case 20:
            { return new Token("CMP_MEI", yytext());
            }
          // fall through
          case 58: break;
          case 21:
            { return new Token("CMP_IGUAL", yytext());
            }
          // fall through
          case 59: break;
          case 22:
            { return new Token("CMP_MAI", yytext());
            }
          // fall through
          case 60: break;
          case 23:
            { return new Token("IF", yytext());
            }
          // fall through
          case 61: break;
          case 24:
            { return new Token("CMP_DYN", yytext());
            }
          // fall through
          case 62: break;
          case 25:
            { return new Token("INT", yytext());
            }
          // fall through
          case 63: break;
          case 26:
            { return new Token("ELSE", yytext());
            }
          // fall through
          case 64: break;
          case 27:
            { return new Token("SHOW", yytext());
            }
          // fall through
          case 65: break;
          case 28:
            { return new Token("THEN", yytext());
            }
          // fall through
          case 66: break;
          case 29:
            { return new Token("ENDIF", yytext());
            }
          // fall through
          case 67: break;
          case 30:
            { return new Token("FLT", yytext());
            }
          // fall through
          case 68: break;
          case 31:
            { return new Token("INICIO_VAR", yytext());
            }
          // fall through
          case 69: break;
          case 32:
            { return new Token("REPEAT", yytext());
            }
          // fall through
          case 70: break;
          case 33:
            { return new Token("STR", yytext());
            }
          // fall through
          case 71: break;
          case 34:
            { return new Token("EQUAL", yytext());
            }
          // fall through
          case 72: break;
          case 35:
            { return new Token("FIN_VAR", yytext());
            }
          // fall through
          case 73: break;
          case 36:
            { return new Token("INICIO_PROG", yytext());
            }
          // fall through
          case 74: break;
          case 37:
            { return new Token("FIN_PROG", yytext());
            }
          // fall through
          case 75: break;
          case 38:
            { return new Token("CTE_HEX", yytext());
            }
          // fall through
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
